packages:
  - "docs"
  - "playground"

catalog:
  vitepress: ^1.6.4
  markdown-it-container: ^4.0.0
  "@types/markdown-it": ^14.1.2
  "@types/markdown-it-container": ^2.0.10

catalogs:
  vue:
    vue: ^3.5.22
